on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy of the (imaginary) stack
    steps:
      - name: Publish the release to Slack
        id: publish-release
        uses: felixdv/publish-release-action@v1.2
        with:
          url: ${{ secrets.SLACK_WEBHOOK_URL }}
          text: "Test-test. SHA: ${GITHUB_SHA}"

      - name: Show the Slack request data
        run: echo "${{ toJSON(steps.publish-release.outputs.request) }}"

      - name: Show the Slack response data
        run: echo "${{ toJSON(steps.publish-release.outputs.response) }}"
