on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy of the (imaginary) stack
    env:
      STAGE: 'production'
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'

      - name: Publish the release to Slack
        id: publish-release
        uses: felixdv/publish-release-action@develop
        with:
          slackWebhookUrl: ${{ secrets.SLACK_WEBHOOK_URL }}
          stage: ${{ env.STAGE }}
          text: ${{ github.event.head_commit.message }}

      - name: Show the Slack response data
        run: echo "${{ toJson(steps.publish-release.outputs.response) }}"

      - name: Show the environment vars
        run: echo "${{ toJson(steps.publish-release.outputs.environment) }}"
