on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy of the (imaginary) stack
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'

      - name: Publish the release to Slack
        id: publish-release
        uses: felixdv/publish-release-action@develop
        with:
          url: ${{ secrets.SLACK_WEBHOOK_URL }}
          text: "\nSHA: ${{ github.sha }}\nRepository: ${{ github.repository }}\nRef: ${{ github.ref }}"

      - name: Show the Slack request data
        run: echo "${{ steps.publish-release.outputs.request }}"

      - name: Show the Slack response data
        run: echo "${{ steps.publish-release.outputs.response }}"

      - name: Show the env vars
        run: echo "${{ steps.publish-release.outputs.environment }}"
